### ISSUE TITLE
Does it use HTTPS?

### ISSUE THREAD

**Issue by shreyasajj** [airmessage/airmessage-server-next#11]
Im trying to add my own reverse proxy on it and the server refuses to work the same way as when i connect to directly to ip address.
Example 192.168.1.90:1359 works fine but airmessage.example.com does not and airmessage.example.com points to http://192.168.1.90:1359. So im a little confused why?

**Comment by larsdennert** [comment]
This is not the appropriate place to ask questions. Use https://www.reddit.com/r/AirMessage/ and even that is not relevant to a local dns service on a LAN having to do with AirMessage.

**Comment by shreyasajj** [comment]
Um this is not on local dns service, the dns service works fine, however it seems that the client wont connect to the backend if the project is upgraded to https for some reason. It like the app cannot use https to verify and implement encrypted tunnel transport

**Comment by tagavari** [comment]
AirMessage does not use HTTPS. Instead, it uses a custom protocol built on top of TCP, which also handles data encryption.

**Comment by shreyasajj** [comment]
Ah I see, It need a tcp router work for this, I assume so. Using Traefik

**Comment by MrOwen** [comment]
@shreyasajj about to set this up. When you set up your TCP router, did you enable TLS, enable TLS with passthrough, or no TLS? And if you used TLS or TLS with passthrough, what did you use for the matching? ``HostSNI(`*`)`` or ``HostSNI(`airmessage.example.com`)``?
