### ISSUE TITLE
Add support for Google accounts with security keys

### ISSUE THREAD

**Issue by StevenPrescott** [airmessage/airmessage-server-next#36]
Right now, you can't sign into a Google account that uses security keys because the in-app browser on Mac doesn't support them in AirMessage. Additionally, with Advanced Protection enabled there is no bypass other than removing and re-enrolling all your keys.

Rather than using the alternative iMessage setup method, it would be nice if the app could either: show the URL (so the user can copy it into their own browser that does support security keys) or be given the option to complete the sign-in directly in their browser.

**Comment by tagavari** [comment]
On macOS 10.15 or later, AirMessage Server 4 uses [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession), which uses Safari by default, or the user's default browser if it supports web authentication sessions. I believe Chrome and Edge support this feature.

On macOS 10.14 or earlier, AirMessage Server 4 will launch the default browser.

[Google's support page on security keys](https://support.google.com/accounts/answer/6103523?hl=en&co=GENIE.Platform%3DDesktop&oco=2) says that security keys are supported on Chrome, Firefox, and Safari.

I haven't tested AirMessage with an account protected by a security key, though the documentation implies this should work in practice. Can you explain how what you're experiencing differs from my understanding of how the process should work?

**Comment by StevenPrescott** [comment]
Sorry for the late reply. I went back and tried again. This time the login with Google option opened in a Safari window that supports keys. Closing this issue :)
