### ISSUE TITLE
AirMessage doesn't request automation permissions

### ISSUE THREAD

**Issue by jsousou77** [airmessage/airmessage-server-next#37]
AirMessage doesn't open a permissions prompt for automation on startup, and it doesn't appear in the automation settings window either, so I can't complete the setup. I've restarted both the settings app and AirMessage multiple times and nothing has worked, I've also tried rebooting. I'm running Mac OS 12.6.3 using Opencore Patcher.

[Video is attached](https://user-images.githubusercontent.com/85518515/215236610-54fa5f0e-a3f8-4822-9841-a018027192fb.mp4)

**Comment by jsousou77** [comment]
Nevermind this is an issue with my system, I think it's actually related to OpenCore Patcher

**Comment by kerta1n** [comment]
Hey @Electronik21 , did you figure out what the issue was? I have a Mac mini 4,1 (mid 2010) running Monterey using OCLP and have the same problem you did.

**Comment by kerta1n** [comment]
It appears running Airmessage server from terminal grants this, but when you execute from the Applications directory, it doesn't request. Bluebubbles is able to do this without a hitch, but Airmessage, not really.
![image](https://user-images.githubusercontent.com/36344851/215520325-bda92f04-bd02-4d37-9bee-3676fc9141e7.png)

**Comment by jsousou77** [comment]
I'm not sure what the problem was, my system seems to be bugged and apps can't request permissions, chrome didn't do that either. I used [TCCPlus](https://github.com/jslegendre/tccplus) to manually add the permissions for accessibility and full disk access, but you can't do that for automation since it requires another app in the database.

After a lot of research and fails I ended up manually editing the sqlite database to add automation, here are the commands I used: 
`sudo sqlite3 /Users/user/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceAppleEvents','me.tagavari.airmessageserver',0,2,2,1,X'fade0c00000000c80000000100000006000000060000000f000000020000001c6d652e74616761766172692e6169726d657373616765736572766572000000070000000e000000000000000a2a864886f7636406010900000000000000000006000000060000000e000000010000000a2a864886f763640602060000000000000000000e000000000000000a2a864886f7636406010d0000000000000000000b000000000000000a7375626a6563742e4f550000000000010000000a543836543641503639360000',NULL,0,'com.apple.MobileSMS',X'fade0c000000003000000001000000060000000200000013636f6d2e6170706c652e4d6f62696c65534d530000000003',0,1674951633);"`

`sudo sqlite3 /Users/user/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceAppleEvents','me.tagavari.airmessageserver',0,2,2,1,X'fade0c00000000c80000000100000006000000060000000f000000020000001c6d652e74616761766172692e6169726d657373616765736572766572000000070000000e000000000000000a2a864886f7636406010900000000000000000006000000060000000e000000010000000a2a864886f763640602060000000000000000000e000000000000000a2a864886f7636406010d0000000000000000000b000000000000000a7375626a6563742e4f550000000000010000000a543836543641503639360000',NULL,0,'com.apple.FaceTime',X'fade0c000000003000000001000000060000000200000012636f6d2e6170706c652e4661636554696d65000000000003',0,1674951634);"`

`sudo sqlite3 /Users/user/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceAppleEvents','me.tagavari.airmessageserver',0,2,2,1,X'fade0c00000000c80000000100000006000000060000000f000000020000001c6d652e74616761766172692e6169726d657373616765736572766572000000070000000e000000000000000a2a864886f7636406010900000000000000000006000000060000000e000000010000000a2a864886f763640602060000000000000000000e000000000000000a2a864886f7636406010d0000000000000000000b000000000000000a7375626a6563742e4f550000000000010000000a543836543641503639360000',NULL,0,'com.apple.systemevents',X'fade0c000000003400000001000000060000000200000016636f6d2e6170706c652e73797374656d6576656e7473000000000003',0,1674951635);"`

Idk if the signatures are system specific but I hope it works for you
